### ISSUE TITLE
BUG: In the project view it always shows the default branch even though something else is running

### ISSUE THREAD

**Issue by mribichich** [timoschwarzer/gitlab-monitor#1]
It seems that the project view always shows the default branch, no matter which one is running

[line with default branch](https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/components/project-card.vue#L8)

It should show the branch that is actually running.
It seems that the info is on the pipeline object in the `ref` property

**Comment by timoschwarzer** [comment]
Closing this in favour of #2
