### ISSUE TITLE
What is the pollingIntervalMultiplier ?

### ISSUE THREAD

**Issue by Mattie112** [timoschwarzer/gitlab-monitor#104]
From the CONFIGURATION.MD:
```
# Multiply all polling intervals by this amount
# (e.g. 0.5 will make gitlab-monitor poll twice as often)
pollingIntervalMultiplier: 1.0
```

But how does it work? We seem to overload the gitlab server with the default settings (and our huge amount of project) but I really don't see any difference between 1 or 10 or 1000. It still seem to do the API calls every 7~15 seconds.

So: what is this value exactly? How often is polled at the default setting of 1? And with what option I can limit this to once every minute or something like that?

**Comment by timoschwarzer** [comment]
Setting a higher value **should** decrease the number of requests per minute. I'll take a look at the source code in a few minutes...

**Comment by Mattie112** [comment]
After some testing it seems that I need to refresh the entire page before it works. All other settings seem to work fine after clicking on "save".

Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by timoschwarzer** [comment]
That may be the case. Glad that it works now! :)
