### ISSUE TITLE
UglifyJs build error when running `yarn run build`

### ISSUE THREAD

**Issue by coleboothman** [timoschwarzer/gitlab-monitor#11]
Hey there,

sorry this is my first time creating an issue on github, not sure if this is the right place for a build error. I'm trying to build the project and I am running into the following error:

```λ yarn run build
yarn run v1.7.0
$ cross-env NODE_ENV=production webpack --progress --hide-modules
Hash: 595d2233e810a76f4a1b
Version: webpack 3.10.0
Time: 18159ms
       Asset       Size  Chunks                    Chunk Names
   icons.svg      86 kB          [emitted]
    build.js     735 kB       0  [emitted]  [big]  main
build.js.map     950 kB       0  [emitted]         main
  index.html  254 bytes          [emitted]

ERROR in build.js from UglifyJs
Invalid assignment [./node_modules/query-string/index.js:8,0][build.js:22681,30]
Child html-webpack-plugin for "index.html":
     1 asset
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I tried googling this error but couldn't find much info on it. Here's an attached screenshot of my steps as well:

![gitlab-monitor build error](https://user-images.githubusercontent.com/14957309/40750321-c0f42336-641b-11e8-9bb5-580520018c49.PNG)

Any idea where I am going wrong here?

**Comment by timoschwarzer** [comment]
Hi Cole!

Thanks for creating this issue. I'll take a look tomorrow... :wink:

**Comment by coleboothman** [comment]
Awesome, vielen Dank fuer deine Hilfe Timo :)

**Comment by timoschwarzer** [comment]
Hmm, weird. It compiles just fine in my CI environment. I will take a closer look on Monday because I currently don't have access to a desktop PC or laptop.

**Comment by coleboothman** [comment]
Interesting - it's worth noting that I can run `yarn run dev` still and make modifications, just not `build`. I did a bit of digging and found that this error pops up sometimes when the webpack version is incompatible. Maybe it's just my machine

**Comment by timoschwarzer** [comment]
Can you try running  `yarn upgrade` and then `yarn build`?

**Comment by timoschwarzer** [comment]
Hi Cole,

I have had access to a computer and could reproduce your issue. I've updated some dependencies, mainly Webpack to version 4. Your build should work now after pulling the changes.

Thank you for reporting the issue! :)

**Comment by coleboothman** [comment]
Wohoo, just saw this when I got into work. Thanks a lot for your help Timo, appreciate it! :)
