### ISSUE TITLE
gitlab 500 Internal Server Error

### ISSUE THREAD

**Issue by vitorcampea** [timoschwarzer/gitlab-monitor#114]
I think it is not working with the public gitlab.

Request:
https://gitlab.com/api/v4/projects?order_by=last_activity_at&per_page=20

Response:
{"message":"500 Internal Server Error"}

**Comment by timoschwarzer** [comment]
We had that before (https://github.com/timoschwarzer/gitlab-monitor/issues/59) and there's nothing we can do but wait for GitLab to fix it. :)

**Comment by OKNoah** [comment]
Are there some conditions that cause this to happen, or just the whole project is broken until Gitlab fixes something? Is there an issue for this on Gitlab?

**Comment by timoschwarzer** [comment]
It seems like there's nothing we can do. I cannot reproduce it, too. I'm using a self-hosted GitLab instance and never had any 500s. Can someone inspect a 500 in the browser dev tools and send back some debug information? (**Make sure to redact sensitive data!**)

**Comment by lovethisshit** [comment]
I think the problem is, that https://gitlab.com/api/v4/projects would get all public projects available on gitlab.com. I managed to solve this by adding the 

`"membership": true`

option to config.json. This will only get projects where I'm a participant.
