### ISSUE TITLE
[Configuration] - Help with configuration

### ISSUE THREAD

**Issue by vitorcampea** [timoschwarzer/gitlab-monitor#115]
Hello,

I need help with the configuration, please.
How do i filter only 4 projects, for example:

- gateway_001
- core
- mobile_app
- anotherGateway

I am trying this
gitlabApi: https://gitlab.com/api/v4
privateToken: -----
showJobs: iconAndName
showUsers: true,
filter: {
  include:  gateway_001|core|mobile_app
}

Thanks for the help!

**Comment by timoschwarzer** [comment]
Hi!

You want to configure your filter as following:

```yaml
filter:
  include: '(gateway_001|core|mobile_app)'
```

I'll close this issue but feel free to continue the conversation :)

**Comment by timoschwarzer** [comment]
Since the filter is regex, you can try it on a regex testing website like this one: https://regex101.com/r/dz53f9/1

**Comment by vitorcampea** [comment]
Thanks, i will take a look
