### ISSUE TITLE
config.json should not be fetched from root-directory

### ISSUE THREAD

**Issue by alexgit2k** [timoschwarzer/gitlab-monitor#126]
It is possible to supply an own configuration in the file config.json at runtime. However, the app fetches them from /config.json so it does not work if the app is running within a subdirectory.

e.g. https://domain.com/monitor/
The configuration must be https://domain.com/config.json but should be fetched from  https://domain.com/monitor/config.json

**Comment by hatemzidi** [comment]
i just found that's possible by editing main.js:31 from 
```
const {data} = await axios.get('/config.json')
```
to 
```
const {data} = await axios.get('./config.json')
```

i'm preparing a PR for that.
