### ISSUE TITLE
Feature: Add ability to edit the local configuration

### ISSUE THREAD

**Issue by motcke** [timoschwarzer/gitlab-monitor#130]
When I'm using the dashboard without predefined configuration, in the first I get to the page, I can have my own configuration. But once I'm done editing the configuration and hit `save`, there's no option to go back and update. 

This makes a problem when I misconfigured some of the configurations (e.g. branch name) and I'm not able to get my result anymore.
It's even worse when the misconfiguration is with the URI/token because then the page is stuck on loading forever. Therefore, editing the configured has to be possible also from the page while it's still loading.

What I'm suggesting is to have a settings gear icon at the corner of the page, where I can always click and go back to the configuration page.

For now, a workaround would be to go to the local storage and remove the config entry.

**Configuration Page**
![Configuration Page](https://user-images.githubusercontent.com/3529897/75462049-4966f880-598c-11ea-9040-564bd177c8dd.png)

**Loading Page**
![Loading Page](https://user-images.githubusercontent.com/3529897/75462140-70bdc580-598c-11ea-90c7-a80400d7160e.png)

**Comment by timoschwarzer** [comment]
https://github.com/timoschwarzer/gitlab-monitor/blob/master/CONFIGURATION.md rtfm ;)
