### ISSUE TITLE
What scopes are required for the API key?

### ISSUE THREAD

**Issue by georgek** [timoschwarzer/gitlab-monitor#134]
I can't see it documented anywhere what scopes are required for the API key. I don't want to give it write access to my Gitlab instance. What are the minimum required scopes?

### [Jump to answer](https://github.com/timoschwarzer/gitlab-monitor/issues/134#issuecomment-683562397)

**Comment by timoschwarzer** [comment]
Hi George!

I think `read_repository` should be enough, though I can't say with 100% confidence. Can you test it and report back? Then I'll add this to the docs. :)

**Comment by georgek** [comment]
It wasn't working for me before with just `read_repository`. I've just noticed why, this is the response from Gitlab:
```
{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api"}
```
So it seems to require "api" scope which is, IMO, too privileged.

**Comment by motcke** [comment]
you must give it API access otherwise it won't work, but there's a problem here since GitLab doesn't give you the option to grant only partial access to the API as you can see in the attached image.

The only solution I see is to create a new user that has only read access and then generate API token for him.


![image](https://user-images.githubusercontent.com/3529897/76084867-87ca6c00-5fb9-11ea-9928-a27e2f32d63c.png)

**Comment by georgek** [comment]
Right, I see. I was misunderstanding the scopes and was afraid of the "api" scope because of the "complete read/write" aspect. Perhaps a better way to do this is instead of using user access tokens requesting a token via the OAuth interface for registered applications?

**Comment by georgek** [comment]
By the way, it works with just "api" scope, no other scopes required it seems.

**Comment by timoschwarzer** [comment]
> It wasn't working for me before with just `read_repository`. I've just noticed why, this is the response from Gitlab:
> 
> ```
> {"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api"}
> ```
> 
> So it seems to require "api" scope which is, IMO, too privileged.

For which request is that?

**Comment by georgek** [comment]
`GET projects?order_by=last_activity_at&per_page=20`

**Comment by timoschwarzer** [comment]
ah, right. Yea seems like we have to wait for GitLab to provide read-only api access...

**Comment by lscheibel** [comment]
Since GitLab 12.10 there is now an option for `read_api` and it works fine:

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#limiting-scopes-of-a-personal-access-token
