### ISSUE TITLE
Question: How to set fixed width for pipeline style?

### ISSUE THREAD

**Issue by Poseiden** [timoschwarzer/gitlab-monitor#138]
how to set fixed width for per pipeline style? Or status color(running status is blue, failed is red, success is green)?

**Comment by timoschwarzer** [comment]
You can apply custom styling in the settings of gitlab-monitor. The classes you'd need to override for status colors and fixed-with project cards are located here: https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/components/project-card.vue#L311
