### ISSUE TITLE
Add Login / Auth Screen

### ISSUE THREAD

**Issue by armandleopold** [timoschwarzer/gitlab-monitor#144]
I would be nice to have a basic login screen with username/password variables mapped to ENV var & Kubernetes secrets for the PASSWORD

**Comment by timoschwarzer** [comment]
gitlab-monitor does not authenticate using user/password credentials but with an Access Token. You have to set your Access Token in your config, which itself can be provided using the `GITLAB_MONITOR_CONFIG` environment variable.
