### ISSUE TITLE
The dashboard only shows at most 20 projects.

### ISSUE THREAD

**Issue by janvojt** [timoschwarzer/gitlab-monitor#155]
If I use the below configuration:

```yaml
maxAge: 0
fetchCount: 60
```
the fetchCount parameter is not used in the `api/v4/projects` call. I am unable to load more than 20 projects. It seems like the paging for `projects` call has not been implemented at all, or is buggy.

**Comment by timoschwarzer** [comment]
Thanks for reporting! Fixed with 2440d3fda558dc36b54406de0aac1ced43b9d8be
