### ISSUE TITLE
Feature: Show gitlab runner status

### ISSUE THREAD

**Issue by philip-n** [timoschwarzer/gitlab-monitor#161]
### Proposal
Add an optional status bar (or similar) that shows the status of the runners, as available via the [API](https://docs.gitlab.com/ce/api/runners.html) (e.g. via `[gitlab.url]/api/v4/projects/[project-id]/runners`).

From my perspective, the main relevant information is "are all runners online" (if not, somebody will need to log in to gitlab anyway). So querying/displaying additional information would be of little benefit.

### Background
For users of self-hosted gitlab instances, the status of the gitlab runners is something to keep an eye on (are all configured runners online? any outages?).

At our company, there's a handful of shared runners for all projects, quite enough to handle the load. Once in a while, a runner might become unavailable for some reason, which does not affect the overall performance. If it goes unnoticed and multiple runners "drop out" over time, it affects our nightly pipelines.

### Quick mock
*A picture says more than a 1000 words...*

![runner-status-mock](https://user-images.githubusercontent.com/3903619/101000240-e4b17d80-355d-11eb-8810-7f757b22d7ff.jpg)

**Comment by timoschwarzer** [comment]
I like that idea! Thanks for the proposal and the mockup. :)

**Comment by timoschwarzer** [comment]
Implemented in #186

**Comment by philip-n** [comment]
Great! Thanks to @dirtcrusher and @timoschwarzer :clap: 

I'm looking forward to deploying this - do you already know when a new image will be pushed to dockerhub?

**Comment by timoschwarzer** [comment]
I still need to move the image to the GitHub registry to have autobuilds again...
