### ISSUE TITLE
Update view only when tab is active

### ISSUE THREAD

**Issue by mribichich** [timoschwarzer/gitlab-monitor#17]
Hi there, I was thinking that for desktop uses, it would be great to check whether the tab is active or not, and depending on that, not send requests to gitlab

Since the tab is not active, the user can't see the changes, so it kinda not make sense to update the view, until the tab get active again.

This way, we could save a lot of requests or load to Gitlab, when the user is not watching

The behavior is transparent to users. Or maybe we could add a config flag, but it doesn't make sense for now.
Maybe in the future if we add notifications for failed builds, then the config flag makes sense, because you'll want to be notify even if the tab is not active

what do you think? I could work on this in this week, and maybe if you want we could also try out notifications separately

**Comment by timoschwarzer** [comment]
That's a really good idea!
I've been working with NotifyJS in the past and it's working very well. https://npmjs.com/package/notifyjs

Also, I had some thoughts about having a simple server that receives webhooks and broadcasts them via Socket.IO to the frontend so we don't have any unnecessary requests at all. This should be optional though. https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#pipeline-events

**Comment by mribichich** [comment]
Thats also a really good one, would decrease request a lot even when the tab is active, which is awesome

ok I'll start working on the non-active non-requests part, and then we could move to that too

**Comment by timoschwarzer** [comment]
That's great! Thank you!

**Comment by LHolst** [comment]
hey after my changes #30 to use fetchCount for pipelines and branches too, the non-active part would be nice. I've searched abit and found https://www.npmjs.com/package/visibilityjs aka https://github.com/ai/visibilityjs.

**Comment by timoschwarzer** [comment]
@LHolst the `Visibility.every` method looks promising.
