### ISSUE TITLE
"Merged Results Pipelines" not shown

### ISSUE THREAD

**Issue by maxfriedmann** [timoschwarzer/gitlab-monitor#192]
We're using only merged results pipelines (see https://docs.gitlab.com/ee/ci/pipelines/merged_results_pipelines.html) in our gitlab, unfortunately they're not shown in your more than awesome dashboard. 

Is there a configuration option I missed where I can activate also showing merged results pipelines? Or is it a missing feature?

**Comment by maxfriedmann** [comment]
Nevermind, switched to our own solution...

**Comment by rubdos** [comment]
Hey, please don't close issues because you are moving to different software. Others are having this issue.
