### ISSUE TITLE
How do we weed out unwanted displays

### ISSUE THREAD

**Issue by Qutianyawangyue** [timoschwarzer/gitlab-monitor#197]
In my project, there are dozens of Piplines at any given time, but we only want to see piplines for a particular branch. How do we weed out unwanted displays

**Comment by timoschwarzer** [comment]
Please take a look here at `projectConfig` → `include`: https://github.com/timoschwarzer/gitlab-monitor/blob/main/CONFIGURATION.md#configuration-options
