### ISSUE TITLE
Feature: Show more than one pipeline per project

### ISSUE THREAD

**Issue by mribichich** [timoschwarzer/gitlab-monitor#2]
It seems that it always shows the last pipeline being run. 

It would be great to see the last X pipelines.
Instead of showing one card per project, you could show the card pipelines as the first citizen, and filter the amount of pipelines per project according to a config value of last pipelines.

this is a pipeline response eg:

```
[
{"id":1163,"sha":"2bfae32771c66a375cde4fa9bd746b7788999ce3","ref":"master","status":"success"},
{"id":1162,"sha":"b5158a9347961d671df6f6933403842ee2f374b1","ref":"14-delete-dialogs-bug","status":"success"},
{"id":1153,"sha":"66e97da8d1f80f3f70e20bedf99defc1c9f1f231","ref":"master","status":"success"},
{"id":1150,"sha":"4636977f5447c97f249199cdba2dcf8d39887575","ref":"13-env-vars-config","status":"success"}, 
... ]
```

Imaging if you have multiples branches building at the same time, you could only see one

**Comment by timoschwarzer** [comment]
So you want a structure like this?

- Project card
  - Branches with pipelines
    - Pipelines of that branch

**Comment by mribichich** [comment]
Right something like that, instead of one card per project/pipeline, you'll have multiple cards per project. and the user can config how many to see

**Comment by timoschwarzer** [comment]
Would be one card per project with multiple pipelines fine?

**Comment by Pegasuz** [comment]
This would be a great feature! Please keep one card per project, but show multiple pipelines below each other.

**Comment by timoschwarzer** [comment]
I will update GitLab Monitor to have this feature in the next weeks, but I can't give an exact time because I am currently short on time. You can always make PRs (even incomplete ones) to help me! :smile:

**Comment by timoschwarzer** [comment]
With the new release (https://github.com/timoschwarzer/gitlab-monitor/releases/tag/1.7), GitLab Monitor will show all branches per default. You can also specify a filter to include or exclude specific branches from showing up. (It's now like @Pegasuz said above)
I'll close this issue for now.
