### ISSUE TITLE
Show jobs status icon and names at the same time

### ISSUE THREAD

**Issue by aleung** [timoschwarzer/gitlab-monitor#20]
At present there is a boolean parameter `showJobNames` to switch between showing status icon or job name. However when job name is displayed it isn't intuitive enough that a job was success or failed. Would be nice to be able to show status icon and name together.

There is two alternatives to config it:

1. Add param `showJobs`. Can be `icon`(default), `name` and `iconAndName`. Deprecate param `showJobNames` and make `showJobs=name` when it's set for backward compatibility.

2. Keep param `showJobNames` and add new boolean param `showJobStatusIcon`.

| showJobNames | showJobSatusIcon | display |
| --------------- | ------------------- | ------- |
| true                    | true                         | icon & name   |
| true                    | false/undefined       | name    |
| false                   | true/false/undefined  | icon      |
| undefined          | true/undefined          | icon      |

I favor alternative 1.

**Comment by timoschwarzer** [comment]
Hi! Thank you for opening this issue! :)

Currently, the job status is indicated by the color if you are displaying the job names. The problem is that the cards get really big if you show icons and names simultaneously.
