### ISSUE TITLE
OAuth2/OIDC Authentication

### ISSUE THREAD

**Issue by EvertonSA** [timoschwarzer/gitlab-monitor#207]
if I deploy this page in the same hostname as my gitlab instance, can it be possible to use user session token to display available pipelines?

---

I as a User would like to access gitlab-monitor and have a option to sign-in using OIDC (Gitlab Group/Instance Application) and gitlab-monitor will show the pipelines I have access (also with extended configuration if I want to filter specific projects).

**Comment by timoschwarzer** [comment]
Right now it's not possible and I don't know if the API authentication accepts session tokens.

**Comment by EvertonSA** [comment]
I did some debug trying with Authentication: Bearer SESSION_TOKEN but it failed miserably.  I might have done something wrong though.

I loved this project but unfortunately, managing these api tokens in local storage might not pleasant the sec team.

**Comment by EvertonSA** [comment]
from my humble frontend knowledge we would need:
- add oidc client
- configure gitlab application
- configure oidc client
- perform OIDC auth
- save session token
- do api calls with session token <- see if it is possible

with my little knowledge I can submit a PR, but I need some clarifications:
- what oidc client to use
- how the mechanism of chosing oidc instead of API token should be handled

from my side I will test a little more how we can use tokens signed by gitlab OIDC to do the api calls

**Comment by EvertonSA** [comment]
again with my little knowledge:
some oidc libs on the internet offer exacly what we need, but it seems they will require vue router...
https://github.com/soukoku/vue-oidc-client

**Comment by EvertonSA** [comment]
@timoschwarzer let me know what lib would you prefer to add to the code base

**Comment by EvertonSA** [comment]
also found this Elm project but it does not work https://gitlab.com/declension/gitlab-pipeline-monitor

**Comment by EvertonSA** [comment]
I abandoned my intention to contribute to this feature. Instead, I'm using gitlab graphql with grafana.
