### ISSUE TITLE
Not sure how to properly set GITLAB_MONITOR_CONFIG when running in docker

### ISSUE THREAD

**Issue by denisvitez** [timoschwarzer/gitlab-monitor#215]
Hi,
I've been trying to run this application in docker, and so far I have had issues with applying the config as a parameter with `GITLAB_MONITOR_CONFIG`

I run the container with:
`docker run --name "CI_DASH" -e GITLAB_MONITOR_CONFIG=/path/dashboard_ci.json -p 10100:80 timoschwarzer/gitlab-monitor`

And the contents of the config file are:
```
{
  "gitlabApi": "https://myserver.com/api/v4",
  "privateToken": "mytoken"
}
```

However, when I try to access the website, it tries to still load data from "gitlab.example.com"

**Comment by timoschwarzer** [comment]
That environment variable is not a path to a file but the actual config string. So set it to something like `"$(cat path/to/config.yaml)"`

**Comment by denisvitez** [comment]
Thank you, this worked, but I had to provide `.json` config not `.yaml` as in your comment :)
