### ISSUE TITLE
Docker container runs in dev mode with build artifacts missing

### ISSUE THREAD

**Issue by bonndan** [timoschwarzer/gitlab-monitor#27]
Several issues are encountered when running the dashboard in docker:

- build.js is missing, see below
- yarn build is missing in Dockerfile (build is not meant to be run at runtime, but at build time)
- the container command activates "dev" script, which is not meant for production use, better run a dedicated server like serve-static or express

**Comment by timoschwarzer** [comment]
Closing as #28 is merged.
