### ISSUE TITLE
Feature: set project visibility level

### ISSUE THREAD

**Issue by Pegasuz** [timoschwarzer/gitlab-monitor#3]
It would be great if we could set the visibility level of the projects we want to see in our dashboard.
In our case, we use the hosted gitlab.com version. Now it shows all the public and private projects. 
We only want to see our private projects.

See also https://docs.gitlab.com/ce/api/projects.html

**Comment by timoschwarzer** [comment]
I will add a `projectVisibility` option soon.

**Comment by timoschwarzer** [comment]
Added a `projectVisibility` option with https://github.com/timoschwarzer/gitlab-monitor/commit/f31b8ee288c7b79a5cae24ae3dc98c4dcf9389dc, which is set to `internal` by default.
