### ISSUE TITLE
Doesn't show pipelines triggered by git tags

### ISSUE THREAD

**Issue by aponski** [timoschwarzer/gitlab-monitor#32]
Hi, 

Some of my projects are being build by gitlab ci when new tag is added (only tags gitlab ci settings). These project are not shown in gitlab monitor (https://timoschwarzer.com/gitlab-monitor/). 

My gitlab monitor configuration 
```json
{
  "gitlabApi": "xxx",
  "privateToken": "xxx",
  "maxAge": 24,
  "fetchCount": 20,
  "pipelinesOnly": true,
  "autoZoom": true,
  "showPipelineIds": true,
  "showJobNames": true,
  "showDurations": true,
  "showUsers": true,
  "projectVisibility": "any",
  "filter": {
    "include": "rnd",
    "exclude": null
  }
}
```

Regards
Arek

**Comment by aponski** [comment]
Please see below response for get single pipeline request. Pipeline triggered by tag. Some data replaced with "xxx". It was working ok, and stopped showing recently in gitlab monitor.

`
{
    "id": xxx,
    "sha": "1e03070971d9324df8f494d9a3e998c3769d2722",
    "ref": "1.0.0.60",
    "status": "success",
    "web_url": "xxx",
    "before_sha": "0000000000000000000000000000000000000000",
    "tag": true,
    "yaml_errors": null,
    "user": {
        "id": xxx,
        "name": "xxx",
        "username": "xxx",
        "state": "active",
        "avatar_url": "xxx",
        "web_url": "xxx"
    },
    "created_at": "2018-09-07T13:59:23.431Z",
    "updated_at": "2018-09-07T14:01:06.310Z",
    "started_at": "2018-09-07T13:59:23.825Z",
    "finished_at": "2018-09-07T14:01:06.306Z",
    "committed_at": null,
    "duration": 101,
    "coverage": null
}
`

**Comment by LHolst** [comment]
IIRC the project-view component knows the filtered branch names and then filters the pipelines accordingly

[project-card.vue#L163-L167](https://github.com/timoschwarzer/gitlab-monitor/blob/464f38e8c86e818cfab5c94301258a219f7f9341/src/components/project-card.vue#L163-L167)

to get the tags into the pipeline list, we need to fetch the tags api per project. then filter the tags and merge them with the branch names

an icon for tag related pipelines would be nice too
