### ISSUE TITLE
Inject a config file into gitlab-monitor docker image

### ISSUE THREAD

**Issue by inorton** [timoschwarzer/gitlab-monitor#34]
Hi,

I'd really like to be able to store a default configuration on disk and have the monitor load that rather than from browser storage.

Is this already possible?

Thanks

Ian

**Comment by grebois** [comment]
I'm also trying to do this, also, once the configuration is applied via web, you need to reset the browser to be able to change it.

**Comment by timoschwarzer** [comment]
@grebois No you don't. There's a button in the very bottom left corner which is hidden until you hover it.
(See CONFIGURATION.md)

**Comment by jasiek** [comment]
I've started looking at this literally an hour ago - it seems that configuration is baked into compiled assets. Perhaps it would be possible to externalize it to a config.json file, which could then be overwritten using a launcher script for nginx.

**Comment by grebois** [comment]
@timoschwarzer found it, sorry, thanks. Still sticking to this request, would be nice to skip this screen when you have the monitor with a valid config. +1

**Comment by inorton** [comment]
Yes, my use case is basically I want to fire up a small docker container hosting this that is pre-configured for my gitlab instance.

**Comment by jasiek** [comment]
I have the code in a branch, will submit a PR.

**Comment by jasiek** [comment]
https://github.com/timoschwarzer/gitlab-monitor/pull/41
