### ISSUE TITLE
Suggestion: Job names as hover/tooltips on job icons

### ISSUE THREAD

**Issue by philip-n** [timoschwarzer/gitlab-monitor#37]
Just found this project and tried it, nice work!

One suggestion: Adding hovers to job icons would allow to have the compact job representation with icons, but easily see e.g. which job failed. I just added it via **:title="job.name"**  to my local version:

`<a class="job-view" target="_blank" rel="noopener noreferrer" :href="project.web_url + '/-/jobs/' + job.id">`

is now

`  <a class="job-view" target="_blank" :title="job.name" rel="noopener noreferrer" :href="project.web_url + '/-/jobs/' + job.id">`

https://github.com/timoschwarzer/gitlab-monitor/blob/c08f65489506b5aab4b9c409784bf104fff26929/src/components/job-view.vue#L2

P.S.: Sorry for not sending a pull request, but I don't have the repository cloned atm.

**Comment by LHolst** [comment]
Good idea.

**Comment by timoschwarzer** [comment]
Merged #38
