### ISSUE TITLE
Sound alerts

### ISSUE THREAD

**Issue by aborderon** [timoschwarzer/gitlab-monitor#39]
Hello,
Your project is very interesting. After going around the features, I think there is one missing ..: p

Indeed, it would be very favorable to be able to integrate the sound alerts from the browsers.

We use gitlab-monitor on a TV in our company but we do not always have eyes on it. A sound alert would be very interesting in the case of an error (build failed etc ...)

**Comment by timoschwarzer** [comment]
Hi @aborderon!

I think this is very doable. But this should be configurable. I'm thinking of:

- Disabling all sounds by default, because I think most people won't use it.
- Specify sounds for success/warning/failure per job and per pipeline.

**Comment by aborderon** [comment]
I'm glad this idea interests you.
Let's say it's the functionality we miss ;)

I agree with you, disable the default sound alerts.
Leave the choice to the user to activate or not the alerts on the different statuses / pipelines.

**Comment by T-vK** [comment]
Notifications would be pretty cool as well. I mean something like:

```
Notification.requestPermission().then(function(result) {
    if (result === 'granted')
        new Notification("Project A", {body:'Job "test" failed...'});
});
```

**Comment by aborderon** [comment]
Yes, you should simply add a web notification using the browser when changing status on the pipeline.

**Comment by T-vK** [comment]
Are you sure? I couldn't find a setting for that and related issues are still open.

**Comment by aborderon** [comment]
Indeed, I may have spoken too fast.
After verification, he seems to have two possibilities.

1. Play a sound (sound.mp3) when changing status on the pipeline.
2. Or use a firefox or chrome extension in addition to web notifications for sound alerts (ex: https://addons.mozilla.org/en/firefox/addon/notification-sound/)

**Comment by T-vK** [comment]
From all I know, Gitlab CI still doesn't have notification support (other than email), so that addon wouldn't do anything.

**Comment by timoschwarzer** [comment]
@T-vK
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/assets/javascripts/vue_merge_request_widget/mr_widget_options.vue#L198

**Comment by T-vK** [comment]
I'm not familiar with gitlab's source code. All I can say is that I don't get desktop notifications, only emails. I checked the project settings as well as the global settings and I was not able to find a setting to enable it. And issues like [this one](https://gitlab.com/gitlab-org/gitlab-ce/issues/28211) are still open.

**Comment by timoschwarzer** [comment]
@T-vK
Can you try to enable notifications for your GitLab instance manually in your browser and then look, whether you get notifications or not?

**Comment by T-vK** [comment]
I only see options to enable email notifications. I already manually enabled them for pipelines. 
Do you actually get desktop notifications?

**Comment by aborderon** [comment]
I do not know if that can help. But a competing project "Node build monitor" has already implemented sound notifications with GitLab (https://github.com/marcells/node-build-monitor)
It uses a file woop.mp3 which is launched at the status change in the pipeline.
It's an observable based on the local code and not directly on the GitLab API (https://github.com/marcells/node-build-monitor/search?utf8=%E2%9C%93&q=sound&type =).

I do not know the source code of gitlab-monitor, but I imagine that you can play a sound file at the change of status of the pipeline in recover the event?

**Comment by timoschwarzer** [comment]
Yes, should definitely be possible. I'm currently just short on time because university is starting for me this week... 😅

**Comment by aborderon** [comment]
New for this feature?

Thank ;)

**Comment by timoschwarzer** [comment]
Hi! I didn't notice that you referenced this issue in a commit...
Can you open a PR for me taking a look at it? Thanks!

**Comment by v1-wizard** [comment]
Hi, guys. @aborderon, what about PR? I really enjoy your feature and I am waiting it. Could you also add changes in documentation with explanation: "how is it work?"?

**Comment by aborderon** [comment]
Hi, sorry for being late, I do not have much time to finish fix this feature right now, I take care of doing the PR as soon as possible.

**Comment by timoschwarzer** [comment]
You can also open a WIP-PR so we can help you with finishing the implementation. :wink:

**Comment by aborderon** [comment]
I just saw that the feature was added by avocadomaster.
See the commit : #https://github.com/avocadomaster/gitlab-monitor/commit/bbf84d224ebb57d0d28793b884110075eb957b24
@timoschwarzer , when do you think ?

**Comment by timoschwarzer** [comment]
It would be great if @avocadomaster could propose a PR... :)

**Comment by avocadomaster** [comment]
I made a PR for my quick fix implementation. Did not make sense for me to build a mute function to comply with Chrome's Autoplay Policy. I disabled this policy for chrome on my machine to allow it to restart without any input.

**Comment by timoschwarzer** [comment]
@avocadomaster Thank you! The PR is merged. I, too, think it doesn't make sense to comply with Chrome's autoplay policy as the workaround is documented in the docs.
