### ISSUE TITLE
[Request] Ability to filter projects based on tags

### ISSUE THREAD

**Issue by Cheezykins** [timoschwarzer/gitlab-monitor#45]
Gitlab allows you to tag a project (not tag as in the Git sense)

It would be great if we could include projects on our dashboard based on these tags, as we have a handful of projects across several groups we would like to include.

You get a list of tags from the v4 API project search scope response:

```
[
  {
    "id": 201,
    // other fields omitted
    "created_at": "2016-08-12T16:05:03.531Z",
    "default_branch": "master",
    "tag_list": [
      "composer",
      "monitored"
    ],
    // other fields omitted
  }
]
```

**Comment by bonniechen1119** [comment]
Hey @timoschwarzer, any news on this?We also want to get pipeline  base on these tags

**Comment by timoschwarzer** [comment]
Hi there!

Sorry for the long delay.
I've just implemented `includeTags` and `excludeTags` filters.
https://github.com/timoschwarzer/gitlab-monitor/commit/3fa066d361b3ee02115dbe2271362aa23417f673
