### ISSUE TITLE
Configuration-filename missing

### ISSUE THREAD

**Issue by alexgit2k** [timoschwarzer/gitlab-monitor#46]
https://github.com/timoschwarzer/gitlab-monitor/blob/master/CONFIGURATION.md says "Your configuration overrides the default configuration, which can be found src/config.default.json", but is missing the filename of my configuration file.

**Comment by timoschwarzer** [comment]
This file definitely exists: https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/config.default.json

I don't understand the problem.

**Comment by alexgit2k** [comment]
Now I understand. With "Your configuration" you mean the configuration within the browser, I thought I can save my configuration to a file like config.json which did not work.

Maybe you can change this to: "Your configuration in the browser overrides the default configuration, which can be found here".
