### ISSUE TITLE
Start with current configuration automatically

### ISSUE THREAD

**Issue by alexgit2k** [timoschwarzer/gitlab-monitor#48]
For usage at a TV I would like to have an autostart-option so that the gitlab-monitor is starting with the supplied configuration automatically instead of showing the configuration and the Save-button for the first time.

**Comment by timoschwarzer** [comment]
Please read the docs: https://github.com/timoschwarzer/gitlab-monitor/blob/master/CONFIGURATION.md#headless-configuration

**Comment by alexgit2k** [comment]
Adding the configuration in the URL on a TV is virtually impossible. My suggestion is to try to fetch https://server/config.js at runtime and use this if it exists.

**Comment by alexgit2k** [comment]
Seems to work with config.json.
