### ISSUE TITLE
Suggestion: Make refresh interval configurable

### ISSUE THREAD

**Issue by mrwulf** [timoschwarzer/gitlab-monitor#52]
With even a modest gitlab install this dashboard makes a lot of requests-- polling every minute (or even every 5) is probably enough for many situations

**Comment by timoschwarzer** [comment]
Currently, it polls projects every 120 seconds. For everything else, the poll interval is dynamically chosen based upon project/pipeline status.
I'm using gitlab-monitor together with a GitLab instance running on a Raspberry Pi and everything works just fine (displaying ~30 projects at a time). So if you have problems with heavy loads on your GitLab server, they probably don't come from gitlab-monitor.
