### ISSUE TITLE
Make default branch always displayed

### ISSUE THREAD

**Issue by ryanoolala** [timoschwarzer/gitlab-monitor#54]
Is there a way to make the default branch pipeline status always on the display even if the last build was more than maxAge?
e.g master was last ran 20 hours ago, maxAge is set to 100 hours but the card was showing "No recent builds"

**Comment by timoschwarzer** [comment]
Hi there!

`maxAge` is compared against `last_activity_at`, which is a bit screwed up on GitLab's side sometimes. So there's nothing I see I can do to accomplish this without hurting performance by always fetching everything.
