### ISSUE TITLE
Trouble with Docker and GITLAB_MONITOR_CONFIG

### ISSUE THREAD

**Issue by JVimes** [timoschwarzer/gitlab-monitor#55]
Using the docker image, I set GITLAB_MONITOR_CONFIG to my config json (verified works), but when I browse to localhost, I get the "Before you can use GitLab Monitor, it has to be configured" page.

Here's how I'm running the container:

    docker run --publish 80:80/tcp --env GITLAB_MONITOR_CONFIG={...json...} timoschwarzer/gitlab-monitor

I opened an interactive session, ran the commands from wrapper.sh, and verified that `/usr/share/nginx/html/config.json` was populated with my config before nginx started.

Does this look like a bug, or am I doing something wrong?

**Comment by JVimes** [comment]
I did a docker pull, cleared cookies, and tried again. Now the page spins forever and I see an error in the console:

![image](https://user-images.githubusercontent.com/6148201/52433351-212f0200-2aca-11e9-98c5-d88d53f72853.png)

Looks like it's using default config instead of mine (and mine got jumbled). If I shell into the container, the environment variable looks right to my eye.

**Comment by timoschwarzer** [comment]
Can you manually `GET /config.json`?

**Comment by JVimes** [comment]
Ah, you're right. Thanks :blush:

I had this in my command line:

    PS> docker run --env GITLAB_MONITOR_CONFIG=$(Get-Content 'C:\path\to\config.json') ...

But no quotes ended up in the environment variable.

Escaping `"` with `\"` fixed it:

    PS> docker run --env GITLAB_MONITOR_CONFIG=$((Get-Content 'C:\path\to\config.json') -replace '"','\"') ...
