### ISSUE TITLE
Add option to display configurable header

### ISSUE THREAD

**Issue by philip-n** [timoschwarzer/gitlab-monitor#56]
### Background
We're currently using the gitlab-monitor to track the status of our various (small and large) repositories.

What we are missing is the possibility to visualize the status of different branches. The background color of each component shows the status of one branch only, and splitting it would probably clutter the view (?).

One idea is to set up different configurations and regularly swap them: Show devel dashboard for 5 minutes, then master dashboard for five minutes, ...

### Feature request
Add an optional header that shows a configurable text. In our case, this would simply be "master" or "devel", to quickly distinguish what is currently displayed.

**Comment by timoschwarzer** [comment]
I've added an optional `title` option. If you use my hosted version of GitLab Monitor, it should be live in some minutes...

Thanks for opening the issue!
