### ISSUE TITLE
Limit number of tags/branches shown

### ISSUE THREAD

**Issue by JVimes** [timoschwarzer/gitlab-monitor#57]
On my team, for better or worse some projects build a lot of tags every day. This throws off the display:

![image](https://user-images.githubusercontent.com/6148201/52449625-3e2cfa80-2af5-11e9-820f-daafc82eeb7e.png)

Suggest `maxTagCount` and `maxBranchCount` options. Each project would show just its latest tags/branches, no more than the count specified.

**Comment by tomsen-san** [comment]
Same here. Was about to open the same issue ;-)

**Comment by timoschwarzer** [comment]
Hi there!
Thank you for opening this issue!

I suggest an option where we can map a regex to a maximum number of pipelines to show. E.g. `"foo.*": 5` will show at most 5 branches/tags that start with "foo". What do you think?

**Comment by JVimes** [comment]
That would work. Although, does it need to be more flexible/complex? If not, less to maintain with a simple implementation. I'm good either way.

**Comment by timoschwarzer** [comment]
You can now set `maxPipelines` for each project filter. See https://github.com/timoschwarzer/gitlab-monitor/blob/master/CONFIGURATION.md
