### ISSUE TITLE
filter not working as expected 

### ISSUE THREAD

**Issue by tomsen-san** [timoschwarzer/gitlab-monitor#58]
Hello, thanks for this really cool tool! :-) 
I have one little problem though. I try to limit the visible projects to the ones of my group/subgroup and I use the 'filter' param for this. I have tried something like this:
```
 "filter": {
    "include": ".*cxa-dsi.*",
    "exclude": null
  }
``` 
and also
```
    "include": "cxa/cxa-dsi",
``` 
and also
```
    "include": "cxa/cxa-dsi.*",
``` 
and also
```
    "include": "/cxa/cxa-dsi.*",
``` 

Always I get projects that do not contain ```cxa-dsi``` in their path. 
So I assume I don't understand what I am supposed to put in or it doesn't work or I have the wrong idea  of how to use the filtering at all. :-) 
Help is appreciated. 

- Thomas

**Comment by timoschwarzer** [comment]
Hi Thomas!

Thank you for opening this issue!
I just found a bug that I introduced yesterday with tag filtering. The include filter always included projects that have no tags.
If you use my hosted version you can test immediately, I updated it to the latest commit.

**Comment by tomsen-san** [comment]
Hi Timo, 
my gitlab lives behind a firewall ... but will happily pick a new docker container :-)
