### ISSUE TITLE
Filter multiple projects

### ISSUE THREAD

**Issue by xen93** [timoschwarzer/gitlab-monitor#62]
I tried to filter only selected projects from our group.

I did it as array but unfortunately it doesn't work for me. Nothing shows up.

`"filter": {
    "include": [ "group/project1", "group/project2", "group/project3" ],
    "exclude": null
  },`

Is it bugged or I misunderstand something?

**Comment by timoschwarzer** [comment]
`include` is a regex.
Your example would be `group/project[1-3]`.

**Comment by xen93** [comment]
Thanks.
