### ISSUE TITLE
Non root docker

### ISSUE THREAD

**Issue by azachar** [timoschwarzer/gitlab-monitor#64]
Hello, 

Is it possible to create a different docker image that is not using root? On Open shift cluster by default images that require root are disabled...

Thank you for considering!

Best regards,
Andrej

**Comment by timoschwarzer** [comment]
Can you run the current image as the `www-data` user?

**Comment by azachar** [comment]
Actually it is more complicated than that, I created a PR for it.

**Comment by timoschwarzer** [comment]
I won't merge this because it will break existing installations. For reference, please see the proposed PR by @azachar above.

**Comment by azachar** [comment]
Thank you for your quick response. 

Are you sure that openshift is a marginal matter? Who is using some extra monitors to display build status - corporates right. The corporates usually do not run on public clouds, but private or on premises one.Thus openshift is very much used. 

Besides, root enabled containers are considered insecure! 

So perhaps a solution could be to create a separate docker for the root less, that is only thing that breaks in openshift.

I look forward to our cooperation!


Cheers,
Andrej

**Comment by timoschwarzer** [comment]
https://cloud.docker.com/repository/docker/timoschwarzer/gitlab-monitor/tags

Can you try the `unprivileged` tag?
