### ISSUE TITLE
Badge variables

### ISSUE THREAD

**Issue by temp** [timoschwarzer/gitlab-monitor#69]
Our badges are broken. We use variables inside our badges, and gitlab-monitor shows a broken image. The generated url/image looks like this: https://<host>/%%7Bproject_path%7D/pipelines
Seems like %{project_path} is not translated. Don't know wether this is a bug in gitlab or in gitlab-monitor.

**Comment by timoschwarzer** [comment]
Hi there!

The badges do work inside GitLab though, right?

**Comment by temp** [comment]
Yes, like a charm ;-)

**Comment by timoschwarzer** [comment]
Should be fixed now. Docker image and hosted version should be up in a few minutes... :wink:
