### ISSUE TITLE
Skipped pipelines

### ISSUE THREAD

**Issue by temp** [timoschwarzer/gitlab-monitor#70]
Would it be possible to filter out skipped pipelines?
Background: We use semantic commits to automatically generate tags and a changelog. Since this is a step in our build pipeline, it results in a commit and a tag for this commit, which only contains the changelog (and other minor things, like a version number in a config file). We skip the build, since it does not contain changes to our code.
The problem is now - the master and the latest tags now don't have a successful build, which results in gitlab-monitor always showing it in gray instead of green (or red).
Would it be possible to filter these pipelines out? We would like to use default branch "master" and the penultimate pipeline.
Hope you get what I mean ;-)

**Comment by timoschwarzer** [comment]
Hi!

Do I get you right saying that you want to display the latest, not-skipped pipeline?

**Comment by temp** [comment]
Yes, for pipelines, and for everything else - like the background color of the card, which is colored based on the default branch (in our case master), for the latest pipeline (always gray in our case, since it is always skipped).

When we merge into master the following happens:
- build of master, commit A
  - changelog is created
  - changelog is commited and pushed, commit B, with [skip ci]
  - tag x.y.z is created and pushed

With these pipelines:
- pipeline 1, for commit A in master (hopefully green after the build)
- pipeline 2, for commit B in master (gray, since skipped)
- pipeline 3, for tag x.y.z (gray, since skipped)

**Comment by timoschwarzer** [comment]
You can now set `hideSkippedPipelines`:

```json
"projectFilter": {
  "*": {
    "hideSkippedPipelines": true
  }
}
```

**Comment by temp** [comment]
Thanks!
