### ISSUE TITLE
Only show projects that have a specific tag

### ISSUE THREAD

**Issue by timvancleef** [timoschwarzer/gitlab-monitor#71]
Hi, i wonder if it's possible to only show projects that have a specific tag?
Let's assume i have many projects, that don't have a consistent naming scheme and are distributed in different groups and subgroups.
I would like to tag some of these projects and only show these projects in the monitor.

As far as i understand it is currently only possible to __also__ include tagged projects, but not to __only__ show tagged ones.

**Comment by timoschwarzer** [comment]
Hi!

Can you try setting `include` to `"^$"` and `includeTags` to `".*"`?

**Comment by timvancleef** [comment]
Unfortunately only setting `includeTags` does not do the job. It will include all projects matching the specified tag as well as all projects which dont have any tags set.

I assume it is because of the part of the if clause in [app.vue](https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/components/app.vue#L108) where you check for `project.tag_list.length === 0 || project.tag_list.some(tag => tag.match(new RegExp(Config.root.filter.includeTags)))`

**Comment by timoschwarzer** [comment]
I've added a new `excludeUntagged` option which should hide all projects that don't have any tags. So for your scenario you want to set `includeTags` to your specific tag and `excludeUntagged` to `true`.

Hope I could help you! :)

**Comment by timvancleef** [comment]
Thanks :)
