### ISSUE TITLE
Allowed failures

### ISSUE THREAD

**Issue by temp** [timoschwarzer/gitlab-monitor#72]
Next feature request :-D

We have pipeline with jobs that are allowed to fail, which gitlab shows with an orange exclamation mark. gitlab-monitor shows these jobs with a red cross, like a normal failed job.
Would be nice to have this visible in gitlab-monitor with an orange exclamation mark, too.

**Comment by tommyseus** [comment]
Maybe fixed when this issue gets solved. 
https://gitlab.com/gitlab-org/gitlab-ce/issues/50813

**Comment by Preveter** [comment]
It seems to be fixed.
It also would be nice to have projects with warnings and no failures painted yellow, but it's another story, i think.

**Comment by timoschwarzer** [comment]
@Preveter thanks for pointing out. I think I can close this issue now.

> It also would be nice to have projects with warnings and no failures painted yellow or green (optionally)

You can open a new issue with more details for that :)
