### ISSUE TITLE
Monitor can't fetch recent pipelines anymore … ?

### ISSUE THREAD

**Issue by nilsborg** [timoschwarzer/gitlab-monitor#79]
Hi Timo!

I've happily using the monitor for the past months and got totally used to my bird's eye view of running pipelines. ❤️ 

Since a couple days, the monitor seems to have trouble fetching the right information about running pipelines. Like, when I leave `maxAge` to the default, it only shows me one project which also has a wrong last run timestamp on it. When I set `maxAge: 0` it shows me everything but all the last run times are off...

Maybe something changes in the Gitlab API? Anyone else with this issue?

Thanks!

**Comment by timoschwarzer** [comment]
Hi!

Do the last change times differ from the times that are displayed in your GitLab instance?
![image](https://user-images.githubusercontent.com/8849554/58405145-17c0aa00-8067-11e9-9d8e-f3d6e8ab2fa2.png)

**Comment by nilsborg** [comment]
heloouu,

yep they do – right? 

<img width="1274" alt="Screenshot 2019-05-27 at 10 07 56" src="https://user-images.githubusercontent.com/1119139/58405284-5a828200-8067-11e9-8922-11d22d3ef62b.png">

**Comment by nilsborg** [comment]
Also just rebuilt and redeployed from source … and set a new access token

**Comment by timoschwarzer** [comment]
@nilsborg That's not the last change time. You can find it on your recent projects dashboard.

**Comment by nilsborg** [comment]
Ah ok well  that says:

<img width="1274" alt="Screenshot 2019-05-27 at 12 20 35" src="https://user-images.githubusercontent.com/1119139/58413756-ddacd380-8079-11e9-83b7-69fa8c6efa65.png">

Though I thought the time in the lower right corner of the project boxes in the monitor is that last time the pipeline ran … ?

**Comment by timoschwarzer** [comment]
Nope, it's the last update time ;)

**Comment by nilsborg** [comment]
Ok then … :) Still, something’s not right.. 3 days vs. 4 days.. Cards not showing currently running pipelines ..
You don’t have these issues?

**Comment by timoschwarzer** [comment]
Nope, everything works just fine for me. Any error messages in your browser console?

**Comment by nilsborg** [comment]
Ahhaaaa haha I'm so sorry. I got confused because of the time thing. Since I thought that was the last run time, and the projects didn't show up when I just re-ran the pipeline without committing anything new....
BUT all of that totally makes sense if that time is the last commit :)
