### ISSUE TITLE
Further project filtering

### ISSUE THREAD

**Issue by sdchapman** [timoschwarzer/gitlab-monitor#8]
We'd like more ways to filter the projects that get displayed. Currently I'm thinking `groups` and `projects` optional parameters that can be used separately or together.

e.g. `?groups=mygroup1,mygroup2&projects=mygroup1/myproject1,mygroup2/myproject2` (or maybe a repeating parameter rather than comma separated)

So if there was a project=mygroup3/myproject3 in the example above, it would not be displayed due to the group filter not including mygroup3. But if it did, or there was no group filter, it would be shown. (The project names are fully qualified because of possible duplicate names leading to ambiguity.)

I didn't want to do a PR out of nowhere as I'm not sure if there's a better/more elegant way (this was just my off the cuff thoughts).

**Comment by timoschwarzer** [comment]
What about this:

- group includes a group and its projects to the filter
- !group excludes a group and its projects
- group/project includes a project to the result
- group/!project excludes a project from the result

**Comment by timoschwarzer** [comment]
With the new release of GitLab Monitor (https://github.com/timoschwarzer/gitlab-monitor/releases/tag/1.7) it's possible to filter projects and branches with a RegExp.

I'll close this issue for now.
