### ISSUE TITLE
Add option to order alphabetically

### ISSUE THREAD

**Issue by nemesisn15** [timoschwarzer/gitlab-monitor#80]
What about a configuration option to change the default sorting? 
Personally I have some use cases where I'd love to see my projects ordered alphabetically, because I have a high number of projects and for me it is hard to find the right project in the dashboard.

**Comment by timoschwarzer** [comment]
Hi! :)

Can you make a PR?
https://github.com/timoschwarzer/gitlab-monitor/blob/master/src/components/app.vue#L109

If you to so, please add a string config option "sortMode" which is either "default" or "alphabetically".

Thanks!

**Comment by motcke** [comment]
In addition, I think it can be very useful to sort by custom order.
For example if I have two projects that one dependent on the other, I'd like to see together.
The same goes for projects that are more important/frequently built, I'd like to see them at the top of the list.
