### ISSUE TITLE
Can't see any project details

### ISSUE THREAD

**Issue by RosiersRobin** [timoschwarzer/gitlab-monitor#84]
So, I've pulled the project, and filled in the default config in `src/config.default.json` and moved that file to the `public folder`.

I've made a API key token (which works) and I use the following URL: `https://gitlab.com/api/v4/users/<my_user_id>`.

This also works, but when I do the project detail API call (`https://gitlab.com/api/v4/users/<my_user_id>/projects/<project_id>`, it throws a 404, so I don't see any project. I've tried seting projects public etc... but nothing seems to work... what am I doing wrong here?

**Comment by timoschwarzer** [comment]
Seems like I need more information to help you.
Does the version at gitlab-monitor.timoschwarzer.com work for you?

**Comment by RosiersRobin** [comment]
The version on gitlab-monitor.timoschwarzer.com does exactly the same thing... I'm using my "private account"

**Comment by timoschwarzer** [comment]
> This also works, but when I do the project detail API call (`https://gitlab.com/api/v4/users/<my_user_id>/projects/<project_id>`, it throws a 404

It seems like you didn't authenticate the API call successfully (just entering the URL in your browser does not work).

See: https://docs.gitlab.com/ee/api/#personal-access-tokens

**Comment by RosiersRobin** [comment]
I usee postman to test the API

**Comment by timoschwarzer** [comment]
If you cannot access your GitLab instance the way it's described in the GitLab documentation, there's not much I can do for you without further information.

**Comment by RosiersRobin** [comment]
How would I access the gitlab instance then? What would be the correct URL for the gitlab online version?

**Comment by timoschwarzer** [comment]
I don't understand your question.
If your GitLab instance runs at http://some.gitlabserver.com/ then the `gitlabApi` config would be `http://some.gitlabserver.com/api/v4`.

**Comment by RosiersRobin** [comment]
I don't run my own gitlab server, I'm using the service from grilab itself.

**Comment by timoschwarzer** [comment]
Then it's `https://gitlab.com/api/v4`

**Comment by RosiersRobin** [comment]
Yes, that is what I'm using. Then after a hell of a time, projects get loaded, but none of them are mine... This is the config I'm using (I'd like to specify a group)... this is my config I'm using:

```
{
  "gitlabApi": "https://gitlab.com/api/v4",
  "privateToken": "<My_generated_token>",
  "maxAge": 168,
  "fetchCount": 20,
  "pipelinesOnly": false,
  "autoZoom": true,
  "showPipelineIds": true,
  "showJobs": "icon",
  "showJobsNameOnlyOn": [],
  "showDurations": true,
  "showUsers": true,
  "projectVisibility": "any",
  "linkToFailureSound": null,
  "title": null,
  "pollingIntervalMultiplier": 1,
  "badges": true,
  "filter": {
    "include": ".*",
    "includeTags": ".*",
    "exclude": null,
    "excludeTags": null,
    "excludeUntagged": false
  },
  "projectFilter": {
    "*": {
      "include": ".*",
      "exclude": null,
      "default": null,
      "showMerged": true,
      "showTags": true,
      "maxPipelines": 0,
      "hideSkippedPipelines": false
    }
  },
  "projectScope": null,
  "projectScopeId": null
}
```

**Comment by timoschwarzer** [comment]
You may want to set `membership` to `true`. (https://github.com/timoschwarzer/gitlab-monitor/blob/master/CONFIGURATION.md)

**Comment by timoschwarzer** [comment]
...and for the group, you want to set `projectScopeId` to `"group"` and `projectScope` to `<your group>`.
