### ISSUE TITLE
Only show most recent Job for given name

### ISSUE THREAD

**Issue by thunderbolt93** [timoschwarzer/gitlab-monitor#85]
If I rerun a job in the pipeline, gitlab-monitor displays a duplicate of the job.
Instead it would be nice to (optionally) only display the newes job of a given name in a pipeline.

I suggest the following patch

[pipeline-view.vue.patch.txt](https://github.com/timoschwarzer/gitlab-monitor/files/3342773/pipeline-view.vue.patch.txt)

but since I'm not a JavaScript programmer, I'd like a second opinion

**Comment by timoschwarzer** [comment]
Closing because #92 is merged.
