### ISSUE TITLE
Usage without dedicated (sub-)domain

### ISSUE THREAD

**Issue by Locour** [timoschwarzer/gitlab-monitor#88]
Can you update the documentation with how to configure gitlab-monitor (and probably its docker equivalent) when you want to use it behind a reverse proxy and a other bath besides the root path. E.g. add the documentation how you implemented `timoschwarzer.com/gitlab-monitor`.

**Comment by timoschwarzer** [comment]
Hi there!

You have to put GitLab Monitor behind a reverse Proxy, for example Træfik.
Then you can point any path to your GitLab Monitor container.

For more information, see https://traefik.io

**Comment by Locour** [comment]
Hi, thanks for your fast reply!

I tried to put it behind an apache reverse proxy but the index.html tries to fetch its additional *.js and *.css resources from the root path.

E.g index.html if fetched from example.com/gitlab-monitor/index.html, the browser wants to load the other resources from example.com/some-file.js.

Is there any prefix or sth. similar that needs to be set to instruct the vue.js app to fetch its sources from a different path?

**Comment by timoschwarzer** [comment]
That *should* already be the case. (See here: https://github.com/timoschwarzer/gitlab-monitor/blob/master/vue.config.js)

**Comment by Locour** [comment]
After some debugging i found out that i set the wrong header ...
May it should be mentioned in the docs that the `X-Forwarded-For`-Header needs to be set?

**Comment by timoschwarzer** [comment]
That's only specific to Apache as far as I know.

But great that it works for You now! :)
Closing this...
